# These are supported funding model platforms

#github: [zukahai, haizukon, haizuka2712]
#patreon: zukahai
tùy chỉnh  : [  "https://www.facebook.com/chiatayde/"  ,   "https://www.facebook.com/algorithmcpp"  ,   "https://www.facebook.com/danggkhoi
